name: Tests

on: [pull_request]

jobs:
  tests:
    name: Test contributors flow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: build
        run: cat Buildfile
